# Generated by Django 6.1 on 2026-08-14 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Type de dépense')),
            ],
            options={
                'verbose_name': 'Type de dépense',
                'verbose_name_plural': 'Types de dépenses',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_depense', models.CharField(choices=[('VETERINAIRE', 'Vétérinaire'), ('ALIMENTAIRE', 'Alimentaire')], max_length=20, verbose_name='Type de dépense')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la facture')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant (€)')),
                ('date', models.DateField(verbose_name='Date de la facture')),
                ('fichier', models.FileField(upload_to='factures/', verbose_name='Fichier scanné')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='animaux.animal', verbose_name='Animal concerné')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date'],
            },
        ),
    ]
