# Generated by Django 6.1 on 2026-08-15 17:12

import Projet_veto.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='fichier',
            field=models.FileField(upload_to='factures/', validators=[Projet_veto.validators.validate_file_extension, Projet_veto.validators.validate_file_size], verbose_name='Fichier scanné'),
        ),
    ]
