# Generated by Django 6.1 on 2026-08-24 15:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0032_finaliser_proprietaire'),
        ('factures', '0002_alter_facture_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Désignation')),
            ],
            options={
                'verbose_name': 'Désignation',
                'verbose_name_plural': 'Désignations',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° de facture'),
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix unitaire (€)')),
                ('prix_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Prix total (€)')),
                ('pour_tous_les_animaux', models.BooleanField(default=False, help_text="Coût partagé également entre tous les animaux enregistrés plutôt qu'attribué à un seul.", verbose_name='Tous les animaux')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='animaux.animal', verbose_name='Animal concerné')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='factures.designation', verbose_name='Désignation')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='factures.facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
    ]
