# Generated by Django 6.1 on 2026-08-24 15:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_designation_facture_numero_lignefacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (€)'),
        ),
    ]
