# Generated by Django 6.1.1 on 2026-09-17 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0006_backfill_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='utilisateur',
            field=models.ForeignKey(help_text="Compte auquel appartient cette facture : chaque compte ne voit que ses propres factures. Déduit automatiquement du propriétaire de l'animal concerné quand il y en a un (cf. save()) ; obligatoire à préciser explicitement pour une facture partagée sans animal renseigné.", on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL, verbose_name='Compte'),
        ),
    ]
