# Generated by Django 6.1.1 on 2026-09-21 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0007_alter_facture_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='utilisateur',
            field=models.ForeignKey(help_text="Compte auquel appartient cette facture (créateur) : visible par ce compte et, le cas échéant, les autres membres de son foyer partagé (cf. accueil.utils.comptes_accessibles). Déduit automatiquement du propriétaire de l'animal concerné quand il y en a un (cf. save()) ; obligatoire à préciser explicitement pour une facture partagée sans animal renseigné.", on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL, verbose_name='Compte'),
        ),
    ]
