"""
Django settings for Projet_veto project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import sys
import environ
from pathlib import Path

from django.contrib import staticfiles

# Initialise environ
env = environ.Env()
environ.Env.read_env()

# `manage.py test` recree une base Postgres jetable a chaque run (cf.
# CLAUDE.md), mais pas le cache Redis (process externe, partage avec le
# dev/prod) : sans ce garde-fou, les compteurs de Projet_veto.throttling
# (limitation de tentatives login/inscription) s'accumuleraient d'un run de
# tests a l'autre et pourraient finir par bloquer 127.0.0.1 pour de vrai.
TESTING = 'test' in sys.argv or 'pytest' in sys.modules

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accueil.apps.AccueilConfig',
    'animaux.apps.AnimauxConfig',
    'vaccins.apps.VaccinsConfig',
    'consultations.apps.ConsultationsConfig',
    'documents.apps.DocumentsConfig',
    'factures.apps.FacturesConfig',
    'notifications.apps.NotificationsConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'Projet_veto.middleware.NoIndexMiddleware',
    'Projet_veto.middleware.ContentSecurityPolicyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not DEBUG:
    # Sert directement les fichiers statiques collectés (STATIC_ROOT) en
    # production — pas de serveur web dédié à configurer devant gunicorn
    # juste pour /static/. Absent en dev : runserver sert déjà les fichiers
    # depuis STATICFILES_DIRS via django.contrib.staticfiles, et STATIC_ROOT
    # n'existe généralement pas tant que `collectstatic` n'a pas tourné (ce
    # que WhiteNoise signalerait par un avertissement à chaque requête).
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'Projet_veto.urls'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'animaux:animal_list'
LOGOUT_REDIRECT_URL = 'login'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Projet_veto.context_processors.notifications_context',
                'Projet_veto.context_processors.preferences_accessibilite_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Projet_veto.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db("DB_URL")  # {
    # 'ENGINE': 'django.db.backends.postgresql',
    # }
}
# Connexions persistantes (évite de rouvrir une connexion Postgres à chaque
# requête sous gunicorn) : désactivé par défaut en dev (chaque requête garde
# sa propre connexion, plus simple avec le rechargement automatique du
# serveur de dev), activé par défaut en production.
DATABASES['default']['CONN_MAX_AGE'] = env.int('CONN_MAX_AGE', default=0 if DEBUG else 60)
DATABASES['default']['CONN_HEALTH_CHECKS'] = not DEBUG

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Fichiers statiques (CSS, JavaScript)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Compression (gzip/brotli) + noms de fichiers hashés (cache navigateur
        # cassé à chaque déploiement) via WhiteNoise, mais seulement une fois
        # `collectstatic` exécuté (production) : le manifeste qu'elle lit
        # n'existe pas tant qu'il ne l'a pas été, donc on garde le stockage
        # standard en dev pour ne rien changer au workflow local.
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage' if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

# Fichiers médias (uploadés par les utilisateurs)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration Celery (rappels de consultation asynchrones)
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Cache partagé (Projet_veto.throttling : limitation de tentatives sur les
# formulaires de connexion/inscription) — sur Redis (base 1, distincte du
# broker Celery en base 0) plutôt que le LocMemCache par défaut de Django, qui
# est propre à chaque process : avec plusieurs workers gunicorn, un cache en
# mémoire locale donnerait une limite réelle de MAX_TENTATIVES x nb_workers
# au lieu de MAX_TENTATIVES. Redis est déjà une dépendance obligatoire du
# projet (cf. CELERY_BROKER_URL ci-dessus).
CACHES = {
    'default': (
        {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'} if TESTING
        else env.cache('CACHE_URL', default='redis://localhost:6379/1')
    ),
}

# Configuration pour l'envoi d'emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT')

EMAIL_USE_SSL = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('EMAIL_HOST_USER')


SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=not DEBUG)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0 if DEBUG else 31536000)
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

# À activer (dans .env) uniquement en production, si et seulement si un
# reverse-proxy de confiance (nginx, load-balancer...) termine le HTTPS et
# transmet bien l'en-tête X-Forwarded-Proto — sinon un client pourrait le
# forger lui-même et tromper Django sur le fait que la requête est en HTTPS.
if env.bool('BEHIND_REVERSE_PROXY', default=False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Contacts techniques : Django y envoie un email (cf. LOGGING plus bas, et le
# comportement intégré de Django sur une erreur 500 non gérée quand DEBUG est
# désactivé) — vide par défaut, donc sans effet tant que non configuré.
# Format .env : "Nom:email@exemple.fr,Autre Nom:autre@exemple.fr"
ADMINS = [tuple(admin.split(':', 1)) for admin in env.list('ADMINS', default=[]) if ':' in admin]
MANAGERS = ADMINS
SERVER_EMAIL = env('SERVER_EMAIL', default=EMAIL_HOST_USER)

# Taille maximale d'un upload conservé en mémoire (au-delà, écrit sur disque) ;
# limite aussi la charge utile mémoire d'une requête multipart.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Informations légales affichées sur la page d'accueil (mentions légales,
# RGPD) — obligatoires pour un site européen, même édité par un particulier
# hors de toute activité professionnelle. À renseigner via le fichier .env
# avant mise en service : les valeurs par défaut ci-dessous sont des
# placeholders, pas des informations réelles.
EDITEUR_NOM = env('EDITEUR_NOM', default="[Ton nom ou pseudonyme]")
EDITEUR_ADRESSE = env('EDITEUR_ADRESSE', default='')
EDITEUR_EMAIL = env('EDITEUR_EMAIL', default=env('EMAIL_HOST_USER', default="[Email de contact à renseigner]"))
EDITEUR_TELEPHONE = env('EDITEUR_TELEPHONE', default='')
HEBERGEUR_NOM = env('HEBERGEUR_NOM', default="[Nom de l'hébergeur à renseigner]")
HEBERGEUR_ADRESSE = env('HEBERGEUR_ADRESSE', default="[Adresse de l'hébergeur à renseigner]")

# =============================================================================
# Journalisation (logs)
# =============================================================================
# Niveau global ajustable via .env sans toucher au code : DEBUG en dev, INFO
# en production par défaut (les erreurs restent de toute façon toujours
# journalisées, quel que soit ce réglage — cf. handlers 'fichier_erreurs' et
# 'mail_admins' ci-dessous, tous deux fixés à ERROR).
LOG_LEVEL = env('LOG_LEVEL', default='DEBUG' if DEBUG else 'INFO')

LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    # Garde les loggers déjà enregistrés par les bibliothèques tierces
    # (celery, weasyprint...) au lieu de les couper, contrairement au défaut
    # de dictConfig.
    'disable_existing_loggers': False,
    'filters': {
        # Bascule certains handlers selon DEBUG, pour ne pas dupliquer les
        # mêmes messages sur deux sorties console à la fois (cf. handlers).
        'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'},
        'require_debug_true': {'()': 'django.utils.log.RequireDebugTrue'},
    },
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname:<8} {name} [{module}:{lineno}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname:<8} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console_dev': {
            # Coloré/lisible pour un terminal de dev (runserver) ; coupé en
            # production au profit de 'console_prod', plus sobre.
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'console_prod': {
            # En production, stdout/stderr reste utile (capturé par
            # systemd/Docker/le supervisor du process gunicorn) en plus des
            # fichiers ci-dessous, mais à un niveau plus posé qu'en dev.
            'level': 'INFO',
            'filters': ['require_debug_false'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'fichier_app': {
            # Journal applicatif général (tout ce qui passe LOG_LEVEL),
            # avec rotation pour ne pas grossir indéfiniment.
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'app.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 Mo
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'fichier_erreurs': {
            # Fichier séparé, uniquement les erreurs (ERROR+) — pour repérer
            # vite un incident sans le noyer dans le reste de l'activité.
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'erreurs.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'mail_admins': {
            # E-mail aux adresses de ADMINS (cf. plus haut) sur toute erreur
            # non gérée, uniquement en production (DEBUG=False) — inutile en
            # dev où la trace complète s'affiche déjà à l'écran. Sans ADMINS
            # configuré, ce handler ne fait simplement rien.
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    # Filet de sécurité : tout logger sans configuration explicite ci-dessous
    # (dont `logging.getLogger(__name__)` de chaque app — animaux, factures...)
    # remonte ici plutôt que de se perdre sur le handler de secours de Python
    # (stderr uniquement, sans fichier ni rotation).
    'root': {
        'handlers': ['console_dev', 'console_prod', 'fichier_app', 'fichier_erreurs'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console_dev', 'console_prod', 'fichier_app'],
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'django.request': {
            # Erreurs serveur (500) et exceptions non interceptées dans une vue.
            'handlers': ['fichier_erreurs', 'mail_admins'],
            'level': 'ERROR',
            'propagate': True,  # remonte aussi vers 'django' (console/app.log)
        },
        'django.security': {
            # CSRF invalide, hôte non autorisé, etc.
            'handlers': ['fichier_erreurs', 'mail_admins'],
            'level': 'WARNING',
            'propagate': True,
        },
        'celery': {
            'handlers': ['console_dev', 'console_prod', 'fichier_app'],
            'level': 'INFO',
            'propagate': False,
        },
        # Bibliothèques tierces bavardes en DEBUG/INFO (cache de polices,
        # étapes de rendu...) : sans ce plafond, chaque graphique de poids ou
        # PDF de fiche animal noierait app.log sous des dizaines de lignes
        # sans intérêt pour le suivi applicatif. Le niveau WARNING+ (erreurs
        # de police manquante, etc.) reste journalisé normalement.
        'matplotlib': {'level': 'WARNING'},
        'PIL': {'level': 'WARNING'},
        'fontTools': {'level': 'WARNING'},
        'weasyprint': {'level': 'WARNING'},
    },
}
