[pytest]
DJANGO_SETTINGS_MODULE = Projet_veto.settings
python_files = tests.py test_*.py *_test.py
python_classes = Test*
python_functions = test_*
addopts = -v accueil/tests.py animaux/tests.py consultations/tests.py factures/tests.py