# Generated by Django 6.1.1 on 2026-09-13 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceAccessibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille_texte', models.CharField(choices=[('normal', 'Normal'), ('grand', 'Grand'), ('tres-grand', 'Très grand')], default='normal', max_length=10, verbose_name='Taille du texte')),
                ('contraste_eleve', models.BooleanField(default=False, verbose_name='Contraste élevé')),
                ('police_lisible', models.BooleanField(default=False, help_text='Police adaptée à la basse vision (Atkinson Hyperlegible).', verbose_name='Police plus lisible')),
                ('reduire_animations', models.BooleanField(default=False, verbose_name='Réduire les animations')),
                ('palette_daltonisme', models.BooleanField(default=False, help_text='Remplace les rouge/vert/orange par la palette Okabe-Ito.', verbose_name='Palette adaptée daltonisme')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_accessibilite', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Préférence d'accessibilité",
                'verbose_name_plural': "Préférences d'accessibilité",
            },
        ),
    ]
