# Generated by Django 6.1.1 on 2026-09-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocageAdresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixe', models.CharField(max_length=50, verbose_name='Formulaire concerné')),
                ('adresse_ip', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('nombre_blocages', models.PositiveIntegerField(default=0, verbose_name='Nombre de blocages')),
                ('bloque_definitivement', models.BooleanField(default=False, verbose_name='Bloqué définitivement')),
                ('derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': "Blocage d'adresse",
                'verbose_name_plural': "Blocages d'adresse",
                'constraints': [models.UniqueConstraint(fields=('prefixe', 'adresse_ip'), name='blocage_unique_prefixe_ip')],
            },
        ),
    ]
