# Generated by Django 6.1.1 on 2026-09-21 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_blocageadresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom du foyer')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Foyer',
                'verbose_name_plural': 'Foyers',
            },
        ),
        migrations.CreateModel(
            name='InvitationFoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_invite', models.EmailField(max_length=254, verbose_name="Email de l'invité")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Jeton')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accueil.foyer', verbose_name='Foyer')),
                ('invite_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Invité par')),
            ],
            options={
                'verbose_name': 'Invitation à un foyer',
                'verbose_name_plural': 'Invitations à un foyer',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MembreFoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adhesion', models.DateTimeField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='accueil.foyer', verbose_name='Foyer')),
                ('invite_par', models.ForeignKey(blank=True, help_text="Compte à l'origine de l'invitation ayant fait entrer ce membre dans le foyer — vide pour le membre fondateur (n'a été invité par personne). Seul ce compte peut retirer ce membre du foyer (cf. accueil.views.retirer_membre_foyer) ; le membre peut toujours se retirer lui-même (cf. accueil.views.quitter_foyer), sans condition.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_invites', to=settings.AUTH_USER_MODEL, verbose_name='Invité par')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membre_foyer', to=settings.AUTH_USER_MODEL, verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Membre de foyer',
                'verbose_name_plural': 'Membres de foyer',
            },
        ),
    ]
