# Generated by Django 6.1.1 on 2026-09-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0003_foyer_invitationfoyer_membrefoyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenceaccessibilite',
            name='mode_sombre',
            field=models.BooleanField(default=False, help_text='Fond sombre et texte clair, pour les yeux sensibles à la lumière.', verbose_name='Mode sombre'),
        ),
    ]
