# Generated by Django 6.1 on 2026-08-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du traitement')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
            },
        ),
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du vaccin')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Vaccin',
                'verbose_name_plural': 'Vaccins',
            },
        ),
        migrations.CreateModel(
            name='SuiviVaccinTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date d'administration")),
                ('date_prochaine_dose', models.DateField(blank=True, null=True, verbose_name='Date de la prochaine dose')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_vaccins_traitements', to='animaux.animal')),
                ('traitement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivi_animaux', to='vaccins.traitement')),
                ('vaccin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivi_animaux', to='vaccins.vaccin')),
            ],
            options={
                'verbose_name': 'Suivi Vaccin/Traitement',
                'verbose_name_plural': 'Suivis Vaccins/Traitements',
                'ordering': ['-date'],
            },
        ),
    ]
