# Generated by Django 6.1 on 2026-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccins', '0004_seed_traitements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccin',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': 'Vaccin', 'verbose_name_plural': 'Vaccins'},
        ),
        migrations.AddField(
            model_name='vaccin',
            name='categorie',
            field=models.CharField(choices=[('OBLIGATOIRE', 'Obligatoire (selon la réglementation)'), ('ESSENTIEL', 'Essentiel (recommandé pour tous)'), ('RECOMMANDE', 'Recommandé selon le mode de vie')], default='RECOMMANDE', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='vaccin',
            name='rappel_interval',
            field=models.CharField(blank=True, help_text='Ex : « Annuel », « Tous les 3 ans ».', max_length=100, verbose_name='Intervalle de rappel'),
        ),
    ]
