# Generated by Django 6.1 on 2026-08-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccins', '0005_vaccin_categorie_rappel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccin',
            name='rappel_interval',
            field=models.CharField(blank=True, help_text='Ex : « Annuel », « Tous les 3 ans ».', max_length=150, verbose_name='Intervalle de rappel'),
        ),
    ]
