# Generated by Django 6.1 on 2026-08-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccins', '0007_set_vaccins_categorie_rappel'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivivaccintraitement',
            name='dose_comprimes',
            field=models.CharField(blank=True, choices=[('1/4', '1/4'), ('1/2', '1/2'), ('1', '1'), ('1 1/2', '1 1/2'), ('2', '2'), ('2 1/2', '2 1/2')], max_length=10, verbose_name='Dose (comprimés)'),
        ),
        migrations.AddField(
            model_name='suivivaccintraitement',
            name='duree_traitement',
            field=models.CharField(blank=True, help_text='Ex : « 7 jours », « 2 semaines ».', max_length=100, verbose_name='Durée du traitement'),
        ),
        migrations.AddField(
            model_name='suivivaccintraitement',
            name='numero_lot',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° de lot du vaccin'),
        ),
        migrations.AddField(
            model_name='suivivaccintraitement',
            name='prise_matin',
            field=models.BooleanField(default=False, verbose_name='Matin'),
        ),
        migrations.AddField(
            model_name='suivivaccintraitement',
            name='prise_midi',
            field=models.BooleanField(default=False, verbose_name='Midi'),
        ),
        migrations.AddField(
            model_name='suivivaccintraitement',
            name='prise_soir',
            field=models.BooleanField(default=False, verbose_name='Soir'),
        ),
        migrations.AlterField(
            model_name='suivivaccintraitement',
            name='date_prochaine_dose',
            field=models.DateField(blank=True, null=True, verbose_name='Date de rappel prévue'),
        ),
        migrations.AlterField(
            model_name='suivivaccintraitement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observations / Annotations'),
        ),
    ]
