# Generated by Django 6.1 on 2026-08-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccins', '0008_suivivaccintraitement_dose_comprimes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traitement',
            options={'ordering': ['classe', 'nom'], 'verbose_name': 'Traitement', 'verbose_name_plural': 'Traitements'},
        ),
        migrations.AddField(
            model_name='traitement',
            name='classe',
            field=models.CharField(choices=[('COMPRIME', 'Comprimé'), ('SOLUTION_BUVABLE', 'Solution buvable'), ('PIPETTE', 'Pipette (spot-on)'), ('COLLIER', 'Collier'), ('SHAMPOOING', 'Shampooing'), ('SPRAY', 'Spray'), ('CREME', 'Crème / Pommade'), ('COLLYRE', 'Collyre (gouttes oculaires)'), ('GOUTTES_AURICULAIRES', 'Gouttes auriculaires'), ('AUTRE', 'Autre')], default='AUTRE', help_text="Forme d'administration du traitement, utilisée pour regrouper le catalogue.", max_length=25, verbose_name='Classe (forme galénique)'),
        ),
    ]
