# Generated by Django 6.1 on 2026-08-20 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccins', '0010_set_traitements_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivivaccintraitement',
            name='dose_comprimes',
        ),
        migrations.AddField(
            model_name='suivivaccintraitement',
            name='dose_unite',
            field=models.CharField(blank=True, choices=[('KG', 'Dose par Kg'), ('ML', 'ml')], max_length=5, verbose_name='Unité de dose'),
        ),
        migrations.AddField(
            model_name='suivivaccintraitement',
            name='dose_valeur',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Dose'),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='classe',
            field=models.CharField(choices=[('COMPRIME', 'Comprimé'), ('SOLUTION_BUVABLE', 'Solution buvable'), ('PIPETTE', 'Pipette (spot-on)'), ('COLLIER', 'Collier'), ('SHAMPOOING', 'Shampooing'), ('SPRAY', 'Spray'), ('CREME', 'Crème / Pommade'), ('GEL', 'Gel'), ('COLLYRE', 'Collyre (gouttes oculaires)'), ('GOUTTES_AURICULAIRES', 'Gouttes auriculaires'), ('AUTRE', 'Autre')], default='AUTRE', help_text="Forme d'administration du traitement, utilisée pour regrouper le catalogue.", max_length=25, verbose_name='Classe (forme galénique)'),
        ),
    ]
