# Generated by Django 6.1 on 2026-08-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date et heure de la consultation')),
                ('motif', models.TextField(verbose_name='Motif de la consultation')),
                ('compte_rendu', models.TextField(blank=True, verbose_name='Compte rendu')),
                ('veterinaire', models.CharField(max_length=100, verbose_name='Nom du vétérinaire')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='animaux.animal')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date'],
            },
        ),
    ]
