# Generated by Django 6.1 on 2026-08-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_finaliser_veterinaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='rappel_task_id',
            field=models.CharField(blank=True, editable=False, help_text="Permet d'annuler le rappel programmé si la consultation est supprimée avant son envoi.", max_length=255, null=True, verbose_name='Identifiant de la tâche Celery de rappel'),
        ),
    ]
