# Generated by Django 6.1 on 2026-08-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Type de document')),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de documents',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('fichier', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('date_ajout', models.DateField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='animaux.animal')),
                ('type_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.typedocument', verbose_name='Type de document')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
