# Generated by Django 6.1 on 2026-08-14 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'animal")),
                ('race', models.CharField(max_length=100, verbose_name='Race')),
                ('espece', models.CharField(choices=[('CHIEN', 'Chien'), ('CHAT', 'Chat'), ('RONGEUR', 'Rongeur'), ('OISEAU', 'Oiseau'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Espèce')),
                ('identification', models.CharField(help_text='Numéro de puce électronique ou tatouage.', max_length=50, unique=True, verbose_name='Identification (puce/numéro)')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('date_deces', models.DateField(blank=True, null=True, verbose_name='Date de décès')),
                ('lof', models.BooleanField(default=False, verbose_name='Inscrit au LOF')),
                ('robe', models.CharField(choices=[('NOIR', 'Noir'), ('BLANC', 'Blanc'), ('GRIS', 'Gris'), ('ROUX', 'Roux'), ('BRUN', 'Brun'), ('TIGRE', 'Tigré'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Robe (couleur)')),
                ('proprietaire', models.CharField(max_length=100, verbose_name='Nom du propriétaire')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Poids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de la pesée')),
                ('valeur', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Poids (kg)')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poids', to='animaux.animal')),
            ],
            options={
                'verbose_name': 'Poids',
                'verbose_name_plural': 'Poids',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('animal', 'date'), name='poids_unique_par_animal_et_date')],
            },
        ),
    ]
