# Generated by Django 6.1 on 2026-08-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='proprietaire',
            field=models.EmailField(max_length=254, verbose_name='Email du propriétaire'),
        ),
    ]
