# Generated by Django 6.1 on 2026-08-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0006_animal_finalize_fk_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='niveau_dangerosite',
            field=models.CharField(choices=[('NON_RENSEIGNE', 'Non renseigné'), ('AUCUNE', 'Aucune'), ('MODEREE', 'Modérée'), ('ELEVEE', 'Élevée')], default='NON_RENSEIGNE', help_text='Indicateur interne de précaution à la manipulation propre au cabinet (ne constitue pas une catégorisation légale).', max_length=20, verbose_name='Degré de dangerosité'),
        ),
    ]
