# Generated by Django 6.1 on 2026-08-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0008_populate_dangerosite_chiens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='identification',
            field=models.CharField(blank=True, help_text="Numéro de puce électronique ou tatouage. Optionnel : l'identification n'est légalement possible qu'à partir de l'âge de 2 à 3 mois.", max_length=50, null=True, unique=True, verbose_name='Identification (puce/numéro)'),
        ),
    ]
