# Generated by Django 6.1 on 2026-08-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0009_alter_animal_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='identification',
            field=models.CharField(blank=True, help_text='Numéro de puce électronique ou tatouage, optionnel', max_length=50, null=True, unique=True, verbose_name='Identification (puce/numéro)'),
        ),
        migrations.AlterField(
            model_name='race',
            name='niveau_dangerosite',
            field=models.CharField(choices=[('NON_RENSEIGNE', 'Non renseigné'), ('AUCUNE', 'Aucune'), ('MODEREE', 'Modérée'), ('ELEVEE', 'Élevée')], default='NON_RENSEIGNE', help_text='Ne constitue pas une catégorisation légale.', max_length=20, verbose_name='Degré de dangerosité'),
        ),
    ]
