# Generated by Django 6.1 on 2026-08-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0011_seed_especes_reptile_arachnide_batracien'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animaux/photos/', verbose_name='Photo'),
        ),
    ]
