# Generated by Django 6.1 on 2026-08-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0012_animal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='categorie',
            field=models.CharField(blank=True, help_text='Ex. type de poil pour les chats, famille pour les NAC.', max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='race',
            name='esperance_vie',
            field=models.CharField(blank=True, max_length=50, verbose_name='Espérance de vie'),
        ),
        migrations.AddField(
            model_name='race',
            name='groupe_fci',
            field=models.CharField(blank=True, help_text='Classification de la Fédération Cynologique Internationale (chiens).', max_length=150, verbose_name='Groupe FCI'),
        ),
        migrations.AddField(
            model_name='race',
            name='infos_complementaires',
            field=models.JSONField(blank=True, help_text='Données additionnelles issues du catalogue (alimentation, habitat, comportement, santé, etc.), propres à certaines espèces.', null=True, verbose_name='Informations complémentaires'),
        ),
        migrations.AddField(
            model_name='race',
            name='legislation_france',
            field=models.CharField(blank=True, max_length=150, verbose_name='Législation (France)'),
        ),
        migrations.AddField(
            model_name='race',
            name='niveau_soin',
            field=models.CharField(blank=True, max_length=50, verbose_name='Niveau de soin requis'),
        ),
        migrations.AddField(
            model_name='race',
            name='nom_scientifique',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom scientifique'),
        ),
        migrations.AddField(
            model_name='race',
            name='origine',
            field=models.CharField(blank=True, max_length=150, verbose_name='Origine'),
        ),
        migrations.AddField(
            model_name='race',
            name='poids_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Poids maximal (kg)'),
        ),
        migrations.AddField(
            model_name='race',
            name='poids_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Poids minimal (kg)'),
        ),
        migrations.AddField(
            model_name='race',
            name='prix_moyen',
            field=models.CharField(blank=True, max_length=50, verbose_name='Prix moyen constaté'),
        ),
        migrations.AddField(
            model_name='race',
            name='sous_categorie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sous-catégorie'),
        ),
        migrations.AddField(
            model_name='race',
            name='taille_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Taille maximale (cm)'),
        ),
        migrations.AddField(
            model_name='race',
            name='taille_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Taille minimale (cm)'),
        ),
    ]
