# Generated by Django 6.1.1 on 2026-09-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0032_finaliser_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='telephone',
            field=models.CharField(blank=True, max_length=14, verbose_name='Téléphone'),
        ),
    ]
