# Generated by Django 6.1.1 on 2026-09-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0033_proprietaire_code_postal_proprietaire_ville_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
