# Generated by Django 6.1.1 on 2026-09-17 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0034_alter_proprietaire_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='utilisateur',
            field=models.ForeignKey(help_text='Compte auquel appartient cette fiche : chaque compte ne voit que ses propres animaux.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animaux', to=settings.AUTH_USER_MODEL, verbose_name='Compte'),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires', to=settings.AUTH_USER_MODEL, verbose_name='Compte'),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AddConstraint(
            model_name='proprietaire',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'email'), name='proprietaire_unique_email_par_compte'),
        ),
    ]
