# Generated by Django 6.1.1 on 2026-09-17 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0036_backfill_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='utilisateur',
            field=models.ForeignKey(help_text='Compte auquel appartient cette fiche : chaque compte ne voit que ses propres animaux.', on_delete=django.db.models.deletion.CASCADE, related_name='animaux', to=settings.AUTH_USER_MODEL, verbose_name='Compte'),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires', to=settings.AUTH_USER_MODEL, verbose_name='Compte'),
        ),
    ]
