# Generated by Django 6.1.1 on 2026-09-21 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0037_alter_animal_utilisateur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='utilisateur',
            field=models.ForeignKey(help_text='Compte auquel appartient cette fiche (créateur) : visible par ce compte et, le cas échéant, les autres membres de son foyer partagé (cf. accueil.utils.comptes_accessibles).', on_delete=django.db.models.deletion.CASCADE, related_name='animaux', to=settings.AUTH_USER_MODEL, verbose_name='Compte'),
        ),
    ]
