# Generated by Django 6.1.1 on 2026-10-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0038_alter_animal_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='certificat_detention',
            field=models.BooleanField(blank=True, help_text='Vide si non renseigné.', null=True, verbose_name='Certificat de détention requis'),
        ),
        migrations.AddField(
            model_name='race',
            name='comportement',
            field=models.TextField(blank=True, verbose_name='Comportement'),
        ),
        migrations.AddField(
            model_name='race',
            name='echelle_dangerosite',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Très doux, sédentaire, idéal pour appartement.'), (2, 'Calme ou légèrement actif, bon compagnon familial.'), (3, 'Actif, besoin de jeu et de stimulation.'), (4, "Énergique, potentiellement destructeur s'il s'ennuie, besoin d'espace."), (5, "Hybride sauvage ou très puissant, besoin d'un environnement spécialisé.")], null=True, verbose_name='Échelle de dangerosité (1 à 5)'),
        ),
        migrations.AddField(
            model_name='race',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Note'),
        ),
    ]
