# Generated by Django 6.1.1 on 2026-10-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0041_importer_insectes_reptiles_arachnides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='niveau_dangerosite',
        ),
        migrations.AlterField(
            model_name='race',
            name='echelle_dangerosite',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Nul'), (2, 'Faible'), (3, 'Moyenne'), (4, 'Élevé'), (5, 'Extrême')], help_text='De 1 (nul) à 5 (extrême). Ne constitue pas une catégorisation légale.', null=True, verbose_name='Degré de dangerosité'),
        ),
    ]
