from django.urls import path
from .views import (
    AnimalListView,
    AnimalDetailView,
    AnimalCreateView,
    AnimalUpdateView,
    AnimalDeleteView,
    PoidsCreateView,
    photo_animal,
    graphique_poids,
    generer_pdf_fiche_animal,
    exporter_animaux_csv,
    exporter_animaux_excel,
    importer_animaux_csv,
    ajouter_espece_ajax,
    ajouter_race_ajax,
    ajouter_organisme_ajax,
    ajouter_robe_ajax,
    ajouter_proprietaire_ajax,
    ProprietaireListView,
    ProprietaireDetailView,
    ProprietaireCreateView,
    ProprietaireUpdateView,
    ProprietaireDeleteView,
)

app_name = 'animaux'

urlpatterns = [
    path('', AnimalListView.as_view(), name='animal_list'),
    path('<int:pk>/', AnimalDetailView.as_view(), name='animal_detail'),
    path('ajouter/', AnimalCreateView.as_view(), name='animal_create'),
    path('<int:pk>/modifier/', AnimalUpdateView.as_view(), name='animal_update'),
    path('<int:pk>/supprimer/', AnimalDeleteView.as_view(), name='animal_delete'),
    path('<int:animal_id>/photo/', photo_animal, name='animal_photo'),
    path('<int:animal_id>/poids/ajouter/', PoidsCreateView.as_view(), name='poids_create'),
    path('<int:animal_id>/poids/graphique/', graphique_poids, name='graphique_poids'),
    path('<int:animal_id>/pdf/', generer_pdf_fiche_animal, name='pdf_fiche_animal'),
    path('exporter/csv/', exporter_animaux_csv, name='exporter_csv'),
    path('exporter/excel/', exporter_animaux_excel, name='exporter_excel'),
    path('importer/', importer_animaux_csv, name='importer_csv'),
    path('especes/ajouter/', ajouter_espece_ajax, name='espece_create_ajax'),
    path('races/ajouter/', ajouter_race_ajax, name='race_create_ajax'),
    path('organismes/ajouter/', ajouter_organisme_ajax, name='organisme_create_ajax'),
    path('robes/ajouter/', ajouter_robe_ajax, name='robe_create_ajax'),
    path('proprietaires/', ProprietaireListView.as_view(), name='proprietaire_list'),
    path('proprietaires/ajouter/', ProprietaireCreateView.as_view(), name='proprietaire_create'),
    path('proprietaires/ajouter-ajax/', ajouter_proprietaire_ajax, name='proprietaire_create_ajax'),
    path('proprietaires/<int:pk>/', ProprietaireDetailView.as_view(), name='proprietaire_detail'),
    path('proprietaires/<int:pk>/modifier/', ProprietaireUpdateView.as_view(), name='proprietaire_update'),
    path('proprietaires/<int:pk>/supprimer/', ProprietaireDeleteView.as_view(), name='proprietaire_delete'),
]