# Generated by Django 6.1.1 on 2026-09-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('RAPPEL_CONSULTATION', 'Rappel de consultation'), ('NOUVEAU_DOCUMENT', 'Nouveau document'), ('FACTURE_A_PAYER', 'Facture à payer'), ('INVITATION_FOYER', 'Invitation à partager un compte')], max_length=50),
        ),
    ]
